FROM python:3.11-slim

WORKDIR /app

# Install build tools for C-based extensions (like parts of pandas/numpy)
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file from your project root into the container
COPY requirements.txt .

# Install the actual libraries
RUN pip install --no-cache-dir -r requirements.txt

# Create the user
RUN useradd -m datauser
USER datauser

CMD ["tail", "-f", "/dev/null"]