<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Symfony\Component\Process\Process;

class VisualizationController extends Controller
{
    /**
     * Show the upload form
     */
    public function index()
    {
        return view('visualise');
    }

    /**
     * Handle the file upload and trigger Python
     */
    public function generate(Request $request)
    {
        $request->validate([
            'dataset' => 'required|file|mimes:csv,xlsx,xls|max:102400',
        ]);

        // 1) Save to the SHARED private folder
        $file = $request->file('dataset');
        $filename = now()->format('Ymd_His_u') . "_" . $file->getClientOriginalName();
        
        // We store in 'uploads' inside the 'local' disk (storage/app/private)
        $storedPath = $file->storeAs('uploads', $filename, 'local'); 
        $inputPath = storage_path('app/private/' . $storedPath);

        // --- CRITICAL FIX START ---
        // Change permissions so the Python container can read the file
        if (file_exists($inputPath)) {
            chmod($inputPath, 0666); 
        }
        // --- CRITICAL FIX END ---

        // 2) Create Output folder in the SHARED public folder
        $reportId = (string) Str::uuid();
        $outRel = "reports/$reportId";
        Storage::disk('public')->makeDirectory($outRel);
        $outDirFull = storage_path('app/public/' . $outRel);
        
        // Ensure the output directory is also writable by Python
        chmod($outDirFull, 0777);

        // 3) MAP PATHS FOR PYTHON CONTAINER
        // Laravel path: /app/storage/app/private/... -> Python path: /app/python_shared_data/...
        $pythonInput = str_replace(storage_path('app/private'), '/app/python_shared_data', $inputPath);
        // Laravel path: /app/storage/app/public/...  -> Python path: /app/python_shared_data/public/...
        $pythonOutput = str_replace(storage_path('app/public'), '/app/python_shared_data/public', $outDirFull);

        // 4) Execute via Docker Bridge
        $command = [
            'docker', 'exec', 'datasci-python',
            'python', '/app/python_scripts/visualize.py', 
            $pythonInput,
            $pythonOutput
        ];

        $process = new Process($command);
        $process->setWorkingDirectory('/app/public'); 
        $process->setTimeout(120);
        $process->run();

        if (!$process->isSuccessful()) {
            return back()->with('error', "Python processing failed: " . $process->getErrorOutput());
        }

        return redirect()->route('visualise.show', ['id' => $reportId]);
    }

    /**
     * Display the generated report
     */
    public function show($id)
    {
        // Path to the JSON summary generated by your Python script
        $summaryPath = storage_path("app/public/reports/$id/summary.json");

        if (!file_exists($summaryPath)) {
            abort(404, "The visualization report was not generated correctly. Check if summary.json exists in storage.");
        }

        $summary = json_decode(file_get_contents($summaryPath), true);

        return view('report', [
            'id' => $id,
            'summary' => $summary,
        ]);
    }
}